/*
 * generated by Xtext
 */
package com.hsveclipse.phototoolkit.ui.contentassist

import com.hsveclipse.phototoolkit.ui.contentassist.AbstractDLSProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class DLSProposalProvider extends AbstractDLSProposalProvider {
}
