/*
 * generated by Xtext
 */
package com.hsveclipse.phototoolkit.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class DLSAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/hsveclipse/phototoolkit/parser/antlr/internal/InternalDLS.tokens");
	}
}
