/*
 * generated by Xtext
 */
package com.hsveclipse.phototoolkit.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.hsveclipse.phototoolkit.services.DLSGrammarAccess;

public class DLSParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private DLSGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.hsveclipse.phototoolkit.parser.antlr.internal.InternalDLSParser createParser(XtextTokenStream stream) {
		return new com.hsveclipse.phototoolkit.parser.antlr.internal.InternalDLSParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Site";
	}
	
	public DLSGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(DLSGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
