/*
 * generated by Xtext
 */
package com.hsveclipse.phototoolkit.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import com.hsveclipse.phototoolkit.ui.internal.DLSActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DLSExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return DLSActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return DLSActivator.getInstance().getInjector(DLSActivator.COM_HSVECLIPSE_PHOTOTOOLKIT_DLS);
	}
	
}
