/*
 * generated by Xtext
 */
package com.hsveclipse.phototoolkit.validation

import org.eclipse.xtext.validation.Check
import com.hsveclipse.phototoolkit.Gallery
import java.util.ArrayList
import com.hsveclipse.phototoolkit.PhototoolkitPackage

/**
 * Custom validation rules. 
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
class DLSValidator extends AbstractDLSValidator {

	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkMultiplePhotos(Gallery gallery) {
		var nameList = new ArrayList<String>
		for (photo : gallery.photos) {
			if (nameList.contains(photo.name)) {
				warning('Photo listed in gallery more than once', 
					PhototoolkitPackage.Literals.GALLERY__PHOTOS,
					INVALID_NAME)

			} else {
				nameList.add(photo.name)
			}
		}
	}
}
