/*
 * generated by Xtext
 */
package com.hsveclipse.phototoolkit.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class DLSUiModule extends com.hsveclipse.phototoolkit.ui.AbstractDLSUiModule {
	public DLSUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
