grammar com.hsveclipse.phototoolkit.DLS with org.eclipse.xtext.common.Terminals

import "http://com.hsveclipse.phototoolkit/1.0"
import "http://www.eclipse.org/emf/2002/Ecore" as ecore

Site : {Site}
	(photos+=Photo|
	galleries+=Gallery)*
;

Gallery: {Gallery}
	'gallery' name=ID '{'
	('description' description=STRING)?
	('photo' photos+=[Photo|ID])*
	'}'
;

Photo: {Photo}
	'photo' name=ID '{'
	('url' uri=STRING)?
	('description' description=STRING)?
	('tag' tags+=STRING)*
	'}'
;
