/*
 * generated by Xtext
 */
package com.hsveclipse.phototoolkit;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DLSRuntimeModule extends com.hsveclipse.phototoolkit.AbstractDLSRuntimeModule {

}
