/*
* generated by Xtext
*/
package com.hsveclipse.phototoolkit;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DLSStandaloneSetup extends DLSStandaloneSetupGenerated{

	public static void doSetup() {
		new DLSStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

